import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body
                style={{
                    backgroundImage: 'url(images/backGround/brickBackground.jpg)',
                    backgroundSize: 'fill',
                    backgroundRepeat: 'no-repeat',
                    backgroundPosition: 'bottom',
                    width: '100vw',

                    height: '100vh',
                }}
            >
                <Header />
                {children}
            </body>
        </html>
    );
}
