export const allBooks: Array<{ title: string }> = [
  { title: "html" },
  { title: "java" },
  { title: "javascript" },
  { title: "typescript" },
  { title: "react" },
  { title: "next" },
  { title: "node" },
  { title: "express" },
  { title: "mysql" },
  { title: "mongodb" },
  { title: "python" },
  { title: "django" },
  { title: "flask" },
  { title: "c" },
  { title: "c++" },
  { title: "c#" },
  { title: "php" },
  { title: "ruby" },
  { title: "rails" },
  { title: "scala" },
  { title: "go" },
  { title: "rust" },
  { title: "swift" },
  { title: "kotlin" },
  { title: "android" },
  { title: "ios" },
  { title: "linux" },
  { title: "ubuntu" },
  { title: "centos" },
  { title: "debian" },
  { title: "redhat" },
  { title: "fedora" },
  { title: "windows" },
  { title: "macos" },
  { title: "unix" },
  { title: "nginx" },
  { title: "apache" },
  { title: "tomcat" },
  { title: "jenkins" },
  { title: "docker" },
  { title: "kubernetes" },
  { title: "aws" },
  { title: "azure" },
  { title: "gcp" },
  { title: "spring" },
  { title: "spring boot" },
  { title: "spring cloud" },
  { title: "spring data" },
  { title: "spring security" },
  { title: "spring batch" },
  { title: "spring integration" },
  { title: "spring jpa" },
  { title: "spring cloud loadbalancer" },
];
